rate: 1.55
tollstart: 05:00
tollstop: 22:00
lanecount: 0
connstring: b2dc7cfa365d2127194cae7c42c5cc41ec7188e750ccc808cc2f8ac43de68e0e87301b1aefce2627412d6aced1ff436b9815f57838e7569901fb666df7bd11ce831a5c827b7b43b84ee73319e2e5cc7d


